#!/usr/bin/node
var calc = require('./lib/calc');

function usage(){
	console.info('USAGE: calc math-expression');
}

if (process.argv.length>2){
	var expr = process.argv.slice(2);
}
else {
	usage();
	process.exit();
	return;
}

expr = expr.join(' '); // Merge all expression tokens

var result = calc.evaluate(expr);

console.log(result);
